[2023-08-30T15:28:10.188+0200] {processor.py:157} INFO - Started process (PID=7062) to work on /Users/france.cama/code/glovo_de_test/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-30T15:28:10.190+0200] {processor.py:829} INFO - Processing file /Users/france.cama/code/glovo_de_test/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-30T15:28:10.190+0200] {logging_mixin.py:151} INFO - [2023-08-30T15:28:10.190+0200] {dagbag.py:539} INFO - Filling up the DagBag from /Users/france.cama/code/glovo_de_test/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-30T15:28:10.204+0200] {logging_mixin.py:151} INFO - [2023-08-30T15:28:10.204+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/france.cama/code/glovo_de_test/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-30T15:28:10.204+0200] {logging_mixin.py:151} INFO - [2023-08-30T15:28:10.204+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-30T15:28:10.204+0200] {processor.py:841} WARNING - No viable dags retrieved from /Users/france.cama/code/glovo_de_test/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-30T15:28:10.277+0200] {processor.py:179} INFO - Processing /Users/france.cama/code/glovo_de_test/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.089 seconds
